//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class DriverInfo
{
    public int DriverID { get; set; }
    public string DriverName { get; set; }
}

public partial class Login
{
    public int UserID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
}

public partial class Products
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
    public int ProductCount { get; set; }
}

public partial class GetProductById_Result
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
    public int ProductCount { get; set; }
}

public partial class ProductViewAll_Result
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
}
