//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class WarehouseDBEntities1 : DbContext
{
    public WarehouseDBEntities1()
        : base("name=WarehouseDBEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<DriverInfo> DriverInfo { get; set; }
    public virtual DbSet<Login> Login { get; set; }
    public virtual DbSet<Products> Products { get; set; }

    public virtual ObjectResult<GetProductById_Result> GetProductById(Nullable<int> productId)
    {
        var productIdParameter = productId.HasValue ?
            new ObjectParameter("ProductId", productId) :
            new ObjectParameter("ProductId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductById_Result>("GetProductById", productIdParameter);
    }

    public virtual int ProductCreateOrUpdate(Nullable<int> productId, string productName, string productDescription)
    {
        var productIdParameter = productId.HasValue ?
            new ObjectParameter("ProductId", productId) :
            new ObjectParameter("ProductId", typeof(int));

        var productNameParameter = productName != null ?
            new ObjectParameter("ProductName", productName) :
            new ObjectParameter("ProductName", typeof(string));

        var productDescriptionParameter = productDescription != null ?
            new ObjectParameter("ProductDescription", productDescription) :
            new ObjectParameter("ProductDescription", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductCreateOrUpdate", productIdParameter, productNameParameter, productDescriptionParameter);
    }

    public virtual ObjectResult<ProductViewAll_Result> ProductViewAll()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductViewAll_Result>("ProductViewAll");
    }
}
